"""table update created_at

Revision ID: 5010f15ae720
Revises: e00986cd5f6d
Create Date: 2022-05-11 15:21:33.046817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5010f15ae720'
down_revision = 'e00986cd5f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_city_created_at'), 'city', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_created_at'), table_name='city')
    op.drop_column('city', 'created_at')
    # ### end Alembic commands ###
